@startuml "dapplet-extension"

cloud ExternalAPI
cloud Ethereum

package "pkg: web-page" {
    node DOM
}

database "InBrowser\nStorage" as Storage

package "pkg: dapplet-extension" {
    [Background]
    [Inpage]
    [Popup]
    [Options]

    Background <..> Inpage : (9) scripts of modules
    Background <..> Popup : (3) feature list
    Background <..> Options

    Background <-> Storage : (2) settings, cache
    Ethereum -down-> Background : (1) modules
    ExternalAPI -down-> Background : (6) augmentation data

    Inpage <-down-> DOM : (5) widgets
}

@enduml