@startuml "dapplet-extension"
scale 800*1200
skinparam componentStyle uml2

database "BusinessCase\nCustom Server" as BusinessCase

package "web page" as Webpage {
    [Overlay]
    frame "injected" {
        [Site Adapter] as Adapter
        [Feature]
        Feature "1..*" -down-> Adapter : configures 
        Feature --> Overlay : opens
    }
    () buttons "1..*" <-up- Adapter : (5) inject
}
actor User
actor Auditor
actor StakeHolder
actor "Business\nDeveloper" as BusDev
actor "Adapter\nDeveloper" as AdapterDev

User .up.> buttons : click
User .left.> Overlay : use

database "Decentralized Storage\nfor Objects and Settings" as Storage

package "pkg: Dapplet Platform" as Platform {
    [Audit/QualityAssurance] as AuditQA
    [Platform Management] as DappletDAO
}

package "pkg: Browser Extension" as Plugin {
    [Background Services] as Background
    [Popup]
    [Feature Injector] as InpageInjector
    [Options]
    Background <-- InpageInjector : (9) load Features \n with deps
    Background <-- Popup : (3) get list of\nFeatures
    InpageInjector --> injected : injects

    Background <-> Options : (2) settings
    BusinessCase .down.> Feature : (6) widget augmentation
    BusinessCase .down.> Overlay : (6) augmentation data

    buttons ..> Feature
}

Platform -up-> Storage
Plugin -up-> Storage
User .up.> Popup : activate\nFeatures
Auditor .up.> AuditQA : Feature Audit
StakeHolder ..> DappletDAO
AdapterDev ..> Adapter : create
' Alignment Helper
Webpage -[hidden]- Plugin
Plugin -[hidden]- Platform
DappletDAO -down-> AuditQA : parameterize
BusDev -down-> BusinessCase: develop

@enduml