@startuml "dapplet-extension"
skinparam componentStyle uml2
skinparam defaultFontSize 16
skinparam legendFontSize 20
skinparam linetype polylne

legend top left
Website, Adapter, Feature
end legend

component "external Service,\nOverlay or Wallet\n" as Service #cyan
package "web page" as Webpage {
    [DOM]
    [Widget]
    [Context]
    frame "injected modules" as injected {
        [Website Adapter] as Adapter #cyan
        [Feature] #cyan
        interface "Widget\nFactory" as widgetFactory #cyan
        interface "Insertion\nPoint" as insertionPoint #cyan
        
        Adapter "  &#8734;" -left-> "1  " DOM : \nparse
        Adapter "  1" <-right-- "  &#8734;" Feature : use
        Adapter "1" --> "&#8734;" widgetFactory : define
        Adapter "1" --down-> "&#8734;" insertionPoint : define 
        insertionPoint "1" *-right-> "&#8734;" widgetFactory : contain
        Context "1" <- "&#8734;" insertionPoint
        Feature "1" ---> "&#8734;" widgetFactory : configure
        widgetFactory --> "&#8734;" Widget : create
        Context "1" <-- "1" Widget : use
        DOM "1" <-- "&#8734;" Context
        
        Widget "&#8734;" <. "1" Service : live data updates
        Widget "1" -> "&#8734;" Service : send data, subscribe
    }
}

@enduml