@startuml "dapplet-extension"
skinparam componentStyle uml2
skinparam defaultFontSize 16
skinparam legendFontSize 20
skinparam linetype polylne

legend top left
Website, Adapter, Feature
end legend

interface "Feature Service" as Service #cyan
package "web page" as Webpage {
    [DOM]
    [Widget]
    [Context]
    frame "injected modules" as injected {
        [Website Adapter] as Adapter #cyan
        [Feature] #cyan
        interface "Widget\nFactory" as widgetFactory #cyan
        interface "Insertion\nPoint" as insertionPoint #cyan
        
        Adapter -left-> DOM
        Adapter <-right-- Feature : use
        Adapter "1" --> "&#8734;" widgetFactory : define
        Adapter "1" --down-> "&#8734;" insertionPoint : define 
        insertionPoint "1" *-right-> "&#8734;" widgetFactory : contain
        Context "1" <- "&#8734;" insertionPoint
        Feature ---> widgetFactory : configure
        widgetFactory --> "&#8734;" Widget : create
        Context "1" <-- "1" Widget : use
        DOM "1" <-- "&#8734;" Context
        
        Feature "1" -> "&#8734;" Service 
        Widget "&#8734;" <. "1" Service : live data update
        Widget "1" -> "&#8734;" Service : send data, subscribe
    }
}

@enduml