@startuml "typescript-examples"

node DOM

package "typescript-examples" {
    [common-lib]
    [twitter-adapter]
    [twitter-feature-1]
    [twitter-feature-2]

    [twitter-adapter] ..left.. DOM

    [twitter-feature-1] <..> [twitter-adapter]
    [twitter-feature-2] <..> [twitter-adapter]

    [twitter-adapter] <..> [common-lib]
}

@enduml