@startuml "typescript-examples"

package "pkg: web-page" {
    node DOM
}

package "pkg: typescript-examples" {
    [common-lib]
    [twitter-adapter]
    [twitter-feature-1]
    [twitter-feature-2]

    [twitter-feature-1] ..> [twitter-adapter]
    [twitter-feature-2] ..> [twitter-adapter]
    [twitter-adapter] ..> [common-lib]
    [twitter-adapter] ..left.. DOM
}

@enduml