name: Playwright Tests
on:
  push:
    branches: [develop]
  pull_request:
    branches: [develop]
jobs:
  test:
    timeout-minutes: 60
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 18
      - name: Install dependencies
        run: npm ci
      - name: Install test dependencies
        run: npm run install:modules:server-interaction
      - name: Install test overlay dependencies
        run: npm run install:test-overlay
      - name: Install Playwright Browsers
        run: npx playwright install --with-deps
      - name: Build extension
        run: npm run build
      - name: Run Playwright tests
        run: npx playwright test
      - uses: actions/upload-artifact@v3
        if: always()
        with:
          name: playwright-report
          path: playwright-report/
          retention-days: 30
